version: "3.9"
services:
  animal-shelter-proxy:
    container_name: animal-shelter-proxy
    ports:
      - '8089:8089'
    image: nginx:latest
    networks:
      - animal-shelter

networks:
  animal-shelter:
    name: animal-shelter
    external: true