version: "3.8"
services:
  animal-shelter-proxy:
    build: .
    container_name: animal-shelter-proxy
    ports:
      - '8090:8089'
    image: nginx:latest
    networks:
      - animal-shelter

networks:
  animal-shelter:
    name: animal-shelter
    external: true