version: "3.8"
services:
  animal-shelter-proxy:
    build: .
    container_name: ${CONTAINER_NAME}
    ports:
      - '${PORT}:8089'
    image: nginx:latest
    networks:
      - animal-shelter

networks:
  animal-shelter:
    name: ${NETWORK}
    external: true