name: Server Deploy Dev

on: 
  push:
    branches: [dev]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    env:
      PORT: 8099
      CONTAINER_NAME: animal-shelter-proxy-dev
      NETWORK: animal-shelter-dev
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build Images
        run: docker compose -f docker-compose-dev.yml up -d --build
