name: Server Deploy

on: 
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    env:
      PORT: 8089
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build Images
        run: docker compose up -d --build
