name: Server Deploy

on: 
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    env:
      HOST_PORT: 8089
      CONTAINER_NAME: animal-shelter-proxy
      NETWORK: animal-shelter
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build Images
        run: docker compose up -d --build
